### ISSUE TITLE
Converting segmentation.tiff to 'imagename'.tiff

### ISSUE THREAD

**Issue by ajr82** [AICAN-Research/FAST-Pathology#45] opened 2022-08-23 15:28 UTC
This is just a query. 

I am running FastPAthology v1.0.1 on Win 11. 

I run a pipeline for all images in my project. Is there a way to name the .tiff result file to 'image filename'.tiff (instead of segmentation.tiff) and create all .tiff files in a single folder for the project instead of them being within subfolders for each WSI image? This will make it easier for importing the annotations into QuPath.

Thank you!

**Comment by smistad** [comment] 2022-08-23 19:23
There is no way to that right now in the software. But it can be accomplished quite easily with a python script which renames/moves the files afterwards.

Is this a standard format/structure that qupath uses for importing data? If so, we can consider making an export function in FastPathology which does this.

**Comment by andreped** [comment] 2022-08-23 19:30
@ajr82 You are probably referring to importing the segmentation TIFF to QuPath using this script, right?
https://github.com/andreped/NoCodeSeg/blob/main/source/importPyramidalTIFF.groovy

If I remember correctly, I have updated this script locally, but have probably not updated it to the NoCodeSeg repo. When I get to work tomorrow I can check and update you on the manner.

Import of predictions from FP into QuPath should then work out-of-the-box, as it did for the older FP version. There should not be a name to change the naming pattern. This is easier solved by updating the groovy script which we use to import the predictions in QuPath.

**Comment by ajr82** [comment] 2022-08-23 19:31
Thank you for your reply. It is not the QuPath standard. I am using the NoCodeSeg scripts and therefore it makes it easy. 
I thought that we could maybe specify the name/folder on the pipeline file and thats why I asked. I can use a Python script. No problem!

**Comment by ajr82** [comment] 2022-08-23 19:32
> @ajr82 You are probably referring to importing the segmentation TIFF to QuPath using this script, right? https://github.com/andreped/NoCodeSeg/blob/main/source/importPyramidalTIFF.groovy
> 
> If I remember correctly, I have updated this script locally, but have probably not updated it to the NoCodeSeg repo. When I get to work tomorrow I can check and update you on the manner.
> 
> Import of predictions from FP into QuPath should then work out-of-the-box, as it did for the older FP version. There should not be a name to change the naming pattern. This is easier solved by updating the groovy script which we use to import the predictions in QuPath.

@andreped, exactly! Okay, thank you very much!

**Comment by andreped** [comment] 2022-08-24 14:30
@ajr82 I just tested inference with FP now and I reproduced the issue. I also found that: 1) the folder structure has changed in the new version of FP and 2) for certain images the mhd/raw format is preferred over TIFF.

- Issue 1) is not really an issue. This can easily be solved by updating the import groovy script in NoCodeSeg.

- Issue 2) is more challenging. QuPath cannot read mhd/raw files. Hence, it would be better to use the same TIFF format for all types of segmentation results. We will look into this, but I assume that you only have TIFF images in your results folder (hopefully).

mhd/raw format will be used if the WSI you are using is very small, too small were a pyramidal format makes sense. However, it is more optimal to use the same format (TIFF) for both, if possible.

I have tested loading segmentations in QuPath, and with the updated script it appears to take a tremendous amount of time. Hence, it is probably better if we try to make a proper fix for this and let you know if this has been fixed in the upcoming release.

**Alternative solution:**
As you are unable to import predictions from FP into QuPath, I would suggest running inference through MIB **(for now)** - the same software you were training in. Then you can import the predictions from MIB into QuPath using this script:
https://github.com/andreped/NoCodeSeg/blob/main/source/importStitchedTIFfromMIB.groovy

Remember to run inference on full WSIs in MIB (on not just patches), because this script expects stitched segmentation TIFF images. Also remember to update the hyperparameters to match your setup:
https://github.com/andreped/NoCodeSeg/blob/main/source/importStitchedTIFfromMIB.groovy#L27

This should work as before. If you are experiencing any issues with running predictions on full WSIs in MIB and importing these in QuPath, please, feel free to ask for help :]

**Comment by andreped** [comment] 2022-08-24 14:31
@ajr82 I also opened an Issue on the NoCodeSeg repo to track this issue. You can also reply there if it is related to interacting with MIB and QuPath:
https://github.com/andreped/NoCodeSeg/issues/12

**Comment by ajr82** [comment] 2022-08-24 15:53
@andreped thank you for looking into this. Like you mentioned, I noticed that some of the WSIs have a mhd/raw output, while others have a .tiff output. I was wondering why and it is good to know now that this it is because of the size. 

I will continue to run the whole WSI/MIB workflow as before.

**Comment by andreped** [comment] 2022-08-24 15:56
@ajr82 import of predictions on full WSI from MIB into QuPath is working fine with the other script in NoCodeSeg?

**Comment by ajr82** [comment] 2022-08-24 18:23
@andreped I have been using both the tile-based and full WSI annotation methods to import into QuPath from MIB. Both methods work well. I do notice subtle changes in the output from both these methods. Although full WSI annotations are much faster and easier. Thank you!

**Comment by andreped** [comment] 2022-08-24 18:34
> Although full WSI annotations are much faster and easier.

Full-WSI prediction is absolutely the way to go! It is also easier to maintain and more streamlined, especially when new WSIs are introduced.

But great that the pipeline is working for you :] Looking forward to seeing the results!

Will update you when the TIFF-stuff is fixed in FP.

**Comment by andreped** [comment] 2022-09-09 16:08
@ajr82 Just fixed the path-thingy in NoCodeSeg to be compatible with the latest release of FastPathology:
https://github.com/andreped/NoCodeSeg/commit/9714fb170beeb28958d4d51cb6bb934bd4935635

@smistad also fixed the formatting issue, such that all generated segmentations from FP should now be stored in the same TIFF-format.

We aim to make a new release of FP next week which includes this fix.

**Comment by ajr82** [comment] 2022-09-09 16:50
Thank you very much!

**Comment by andreped** [comment] 2022-09-09 17:03
@ajr82 For testing the updated NoCodeSeg script, could you use the nightly release of FastPathology? It is available from here:
https://github.com/smistad/FAST/actions/runs/2866558364

Alternatively, you can download the latest binary pre-release by clicking this link: [Archive package (zip)](https://github.com/smistad/FAST/suites/7831098478/artifacts/331204004)

Let me know if that solves you problems :)

**Comment by andreped** [comment] 2022-10-20 08:25
@ajr82 Hello! Just letting you know that this has been fixed in the latest artifact, which will be made available as a release soon.

See this thread for some information regarding the issue https://github.com/AICAN-Research/FAST-Pathology/issues/49

On Windows, you can download this artifact (**note that you have to be signed into GitHub to see it**):
https://github.com/AICAN-Research/FAST-Pathology/actions/runs/3282310803

Just click the file `Windows package` and it should download the windows installer for you.

@sahpet You could also test if you are able to run your segmentation models and import these into QuPath, if you have the time.

**Comment by ajr82** [comment] 2022-10-20 12:17
Thank you very much!

**Comment by andreped** [comment] 2022-10-20 13:34
@ajr82 I'm closing this issue for now. If you are having any problems related to this, please, reopen. For other issues, make a new issue. And of course, please, report to me if it worked :) Good luck!

**Closed** 2022-10-20 13:35 UTC
Labels: bug

**Comment by andreped** [comment] 2022-12-06 10:44
@ajr82 this fix has now been made available in the latest release:
https://github.com/AICAN-Research/FAST-Pathology/releases/tag/v1.1.0

All segmentation results should now be stored in the same pyramidal TIFF format, which in turn means that we can import these in QuPath seemlessly.
