### ISSUE TITLE
Alignment issue with overlay

### ISSUE THREAD

**Issue by SahPet** [AICAN-Research/FAST-Pathology#61] opened 2023-02-26 12:04 UTC
Hi!

There is an alignment issue with the overlay. Using the newest release. Somehow the rendered overlay is unaligned for the bottom 1/4 of the images only - see the discontinuous lines in the images below. I'm predicting on pyramidal tiffs (Philips):

![2023-02-26 13_01_22-FastPathology - NEGATIVE_214A4HESHES20210222111056](https://user-images.githubusercontent.com/43611111/221409334-de8c652e-7e89-44d4-9be5-f89fe182b8f4.jpg)
![2023-02-26 13_01_59-FastPathology - NEGATIVE_212A2HESHES20210222110742](https://user-images.githubusercontent.com/43611111/221409335-6e3e8b02-1912-47f8-b81c-a07061fe7c47.jpg)

**Comment by andreped** [comment] 2023-02-26 12:18
We have observed the same for the cellSens VSI format in this issue https://github.com/AICAN-Research/FAST-Pathology/issues/38

However, it is surprising that this is also an issue for the Philips TIFF format. Although this alignment issue maybe looks a little different? For the VSI format the alignment offset is the same for the entire image, whereas for your snapshots it almost seems like some regions have more offset than others. I might be wrong though. For instance, see middle region of bottom image.

Any ideas, @smistad?

**Comment by smistad** [comment] 2023-02-26 12:41
Strange..., I have not seen this before. 
Was this error introduced in the latest release, did it visualize properly before?
Can you share the data/model so i can reproduce it?

**Comment by SahPet** [comment] 2023-02-26 13:37
Hi Erik! I'm not sure if was there before the updata. I can send you the model and an example slide.

**Comment by andreped** [comment] 2023-02-26 13:40
> Was this error introduced in the latest release

Note that @SahPet was using one of the latest artifacts, but I believe this was also a problem for the latest release.

> Hi Erik! I'm not sure if was there before the update. I can send you the model and an example slide.

@SahPet also send @smistad the corresponding FPL you used for produce this result.

**Comment by SahPet** [comment] 2023-02-26 13:43
I've sent the model, fpl-file and example tiff on filesender now.

**Comment by smistad** [comment] 2023-03-02 14:35
This error was due to an incorrect calculation of patch positions at the bottom left most patch (and potentially top right most patch). It was fixed in https://github.com/smistad/FAST/commit/dc8eaf75a6412c6cada675fe3e7d71b7650a57b7 and will be included in FastPathology in the future. Thanks for reporting this issue.

![image](https://user-images.githubusercontent.com/176325/222458341-e1823978-203d-4429-816b-9e26059e753d.png)

**Closed by smistad** 2023-03-02 14:35 UTC
Labels: bug
